apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: booking-api
  namespace: booking
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: booking-api
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: {duration: 30s}
        - setWeight: 50
        - pause: {duration: 30s}
        - setWeight: 100
  template:
    metadata:
      labels:
        app: booking-api
    spec:
      containers:
        - name: booking-api
          image: public.ecr.aws/docker/library/nginx:1.27-alpine
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: booking-api
  namespace: booking
spec:
  selector:
    app: booking-api
  ports:
    - name: http
      port: 80
      targetPort: http
