apiVersion: v1
kind: Service
metadata:
  name: {{ include "booking-api.name" . }}
  labels:
    {{- include "booking-api.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "booking-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
